### ISSUE TITLE
SSD for Windows 10

### ISSUE THREAD

**Issue by columbuscyclist** [shiruken/hackintosh#1]
This is an amazing guide. Thanks for putting it together. I'm getting ready to build my first Hackintosh and had a quick question. Would it be possible to use a SSD instead of an M.2 drive for the windows install? If so, would there be any changes in the installation process?

**Comment by shiruken** [comment]
Yeah that won't be a problem. I'd still recommend disconnecting all the other drives to prevent Windows from screwing up their EFI partition(s) during the installation. You may still run into difficulties when Windows tries to update but that can be fixed after the fact or avoided by pulling drives when you update the OS.

**Comment by columbuscyclist** [comment]
Makes sense. If you pull the Mac drive (which I think is where the EFI partition would live) can the machine still boot into the windows drive? Thanks.

**Comment by shiruken** [comment]
It should work because Windows has its own boot manager on the EFI partition of its drive. Things get a little more complicated if both OSes are installed on two volumes on the same physical drive though.

**Comment by columbuscyclist** [comment]
Good. That's what I thought. Definitely will keep them on different drives. I'm getting ready to buy all the parts in the next week or so. I've been lurking on r/hackintosh for 6 months preparing to replace my Mac Pro 3,1. It's served me well for 11 years, but showing it's age.
