### ISSUE TITLE
Internal USB 3.0 connector is for port 10 and 9

### ISSUE THREAD

**Issue by marsjo** [shiruken/hackintosh#12]
This Repository was really useful and it helped me a lot! 
I just have a short hint:
The internal USB 3.0 connector that is named HS/SS 10 is a double USB head for HS/SS 10 and 09.

**Comment by shiruken** [comment]
Good to know. However, since the NZXT H510 only has a pair of front ports, there is no actual HS09/SS09 according to [USBMap](https://github.com/corpnewt/USBMap).
