### ISSUE TITLE
Slow boot due to Samsung SSD TRIM on macOS Monterey

### ISSUE THREAD

**Issue by shiruken** [shiruken/hackintosh#15]
Since upgrading to macOS Monterey, boot times have increased considerably to several minutes. I originally attributed this to problems with Bluetooth in the latest version of macOS (#13), however it appears that the actual culprit may be the Samsung Evo 970 SSD used as my boot drive. There are [outstanding issues with TRIM on Samsung SSDs](https://github.com/dortania/bugtracker/issues/192) that seem to have been exasperated by macOS Monterey.

It is unclear why exactly this is resulting in longer boot times since my configuration has [`SetApfsTrimTimeout=-1`](https://github.com/shiruken/hackintosh/blob/be89aaebe2ed448bcaaa6efcee230b1d6e5bc905/EFI/OC/config.plist#L740), which _should_ result in the standard timeout of ~10 seconds. However, this comes with the risk of not completing the full TRIM operation and could put additional wear on the drive.

See Also:
* [SSD hall of fame needs new entries](https://github.com/dortania/bugtracker/issues/192)
* [tonymacx86: General NVMe Drive Problems (Fatal)](https://www.tonymacx86.com/threads/general-nvme-drive-problems-fatal.316546/)
* [tonymacx86: Extremely slow 6-7 minute boot time with Monterey 12.0.1](https://www.tonymacx86.com/threads/extremely-slow-6-7-minute-boot-time-with-monterey-12-0-1.316614/)

**Comment by shiruken** [comment]
`SetApfsTrimTimeout` seems to have no effect on boot times, possibly indicating that long boot times are **not** being caused by the problematic Samsung SSD TRIM operation. _Boot time measured from motherboard logo to macOS login screen. Used authorized restart to bypass FileVault 2 login._

| SetApfsTrimTimeout | Boot 1 | Boot 2 | Boot 3 |
|-------------------:|:-------:|:-------:|:-------:|
|                 -1 |   2:55  |   2:55  |   2:55  |
|                999 |   2:54  |   2:55  |   2:55  |
|         4294967295 |   2:53  |   2:56  |   2:54  |

Just to be safe, updated configuration such that `SetApfsTrimTimeout=4294967295` (2cf0bfd). While this won't resolve slow booting, it will guarantee the TRIM operation completes.

**Comment by a17uk** [comment]
I am using 980Pro and I have the same issue. SetApfsTrimTimeout settings won't affect the long boot time.

**Comment by 2600box** [comment]
FWIW, I shifted my install from a Samsung 970 EVO to WD Black drive for this very reason. Continuing to use the Samsung for additional storage.

**Comment by shiruken** [comment]
Per [OpenCore 0.7.9](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.9):

> On macOS 12+, it is no longer possible to set trim timeout for APFS filesystems. However, trim can be disabled when the timeout value is set to 0.

Setting `SetApfsTrimTimeout=0` now results in system boot of less than 10 seconds. This "fix" is less than ideal and will lead to ever increasing performance degradation on the SSD. Occasionally booting with `SetApfsTrimTimeout=-1` should theoretically help alleviate this risk.
