### ISSUE TITLE
Macos 12.6

### ISSUE THREAD

**Issue by jslattery26** [shiruken/hackintosh#16]
I have an almost identical build to yours. Have been following your repo for a while now, to compare when I run into errors. I've been _really_ struggling with macos 12.6. I'm getting this weird issue where after running perfect for a while everything slowly runs to a halt. I've done all the debuggingI can, i'm about ready to just clean wipe and start over.

Just curious if there's a reason you are still on 12.5? Did I miss some warnings about 12.6? What are your thoughts about upgrading to ventura?

Appreciate this awesome repo, let me know if I can help contribute at all.

**Comment by jslattery26** [comment]
I believe a lot of my issues come from using MacPro7,1 and having two monitors. Every time i reboot i have to replug the DVI cable from one of my monitors -- it's a pain. Have you done anything special in terms of driver updates/configuration/etc for your GPU? I have the same one.

**Comment by shiruken** [comment]
FYI I updated to macOS Ventura 13.0.1 today without issue (3ed26cae7971d074f9884e00c7c79c27516ea3ae). Kinda doubt the slow-downs will improve but we'll see!
