### ISSUE TITLE
Bluetooth on Opencore 0.9.1, Ventura

### ISSUE THREAD

**Issue by jslattery26** [shiruken/hackintosh#18]
Hey again, how's bluetooth working for you? 

I've found that if i turn it off, it won't come back on. I'm also having issues pairing.

Have you had success using Airdrop, Sidecar or Continuity(using iPhone as a webcam)?

**Comment by shiruken** [comment]
I've occasionally encountered issues with turning Bluetooth on, but not consistently. I don't use any of those other features so I haven't been able to test them.
