### ISSUE TITLE
Unable to enable System Integrity Protection (SIP)

### ISSUE THREAD

**Issue by shiruken** [shiruken/hackintosh#2]
Attempts to enable System Integrity Protection (SIP) by setting `CsrActiveConfig=0x00` have been unsuccessful. Whenever the parameter is changed from `0x67` (SIP disabled), the system encounters memory allocation errors after entering the password during FileVault2 preboot. Restoring this setting allows the system to operate as expected.

![0C0J8Dj](https://user-images.githubusercontent.com/867617/70383856-dfb1f200-193a-11ea-87df-86591a74202b.png)

**Comment by shiruken** [comment]
Still cannot enable SIP after upgrading to 10.15.2

**Comment by shiruken** [comment]
Still cannot enable SIP after upgrading to 10.15.3 without encountering same boot issues.

**Comment by kornerson** [comment]
I am planning to build exactly the same hack. I was wondering if this issue with SIP only happens with filevault, as Im not interested on activating it

**Comment by shiruken** [comment]
I wouldn't be surprised if FileVault is the cause of this issue since plenty of vanilla installs can re-enable SIP after the initial setup. Unfortunately I don't really have a way to test it. Good luck with your build.

**Comment by KrisTheCanadian** [comment]
Does anyone have an update on this bug?

**Comment by mochadwi** [comment]
why this build not using OpenCore instead? https://dortania.github.io/OpenCore-Install-Guide/why-oc.html#opencore-features

@shiruken

**Comment by shiruken** [comment]
I don't currently have the time to learn about OpenCore and can't risk taking this system offline for an extended period of time to figure it out. I do have plans to do a new installation using OpenCore sometime next year.

**Comment by nyhtml** [comment]
Shouldn't you be using **0x3E7** instead of **0x67** for the [CsrActiveConfig](https://www.dualbootpc.com/guide/csractiveconfig/)?
It probably won't make a difference but my Z270X using some steps of your guide was helpful to get Big Sur running.
![Big Sur](https://user-images.githubusercontent.com/2177262/111317681-beaa7780-863a-11eb-929a-db6d3891db31.png)
