### ISSUE TITLE
Would this need much updating if I have a z370 motherboard?

### ISSUE THREAD

**Issue by Tuaev** [shiruken/hackintosh#20]
Hi Colin, I have almost a similar build to yours except that I have a Z370 Gaming Pro Carbon motherboard. 
Do you know if your current files will work on a Z370 or if will there be much to modify?  Thanks

**Comment by shiruken** [comment]
The Z370 Gaming Pro Carbon is from a completely different manufacturer (MSI), so it's quite likely the configuration (USB port mapping, Bluetooth + Wi-Fi, etc.) will need to be different. You should just follow the [original Dortania OpenCore Installation Guide](https://dortania.github.io/OpenCore-Install-Guide/).
