### ISSUE TITLE
wifi not working after update to itlwm 2.3 stable

### ISSUE THREAD

**Issue by bobmarinho** [shiruken/hackintosh#23]
Hey, I've got exactly the same hardware as you (CPU, GPU and motherboard)...and after the update to itlwm 2.3 stable my wifi simply stopped to work. Do you have any idea of what is going on? Btw, i'm on Sonoma 14.5. and Opencore 1.0

Thanks!

**Comment by shiruken** [comment]
That's strange. Have you tried rolling back to an older version of itlwm to see if the issues are caused by v2.3?

**Comment by bobmarinho** [comment]
Actually I had to use the AirportItlwm_v2.3.0_stable_Sonoma14.4 and now it's working again!
;)

**Comment by shiruken** [comment]
Great!
