### ISSUE TITLE
Wifi is not working

### ISSUE THREAD

**Issue by wxy524** [shiruken/hackintosh#4]
I have not tried directly from windows yet. I use exactly same mobo as yours but no WIFI at all.  I have same build as yours.  I don't see you installed any wifi driver. Any suggestion here?

**Comment by wxy524** [comment]
Based my research, looks like this onboard intel wifi won't work with MacOS. Do you buy any extra wifi/BT card?

**Comment by shiruken** [comment]
Correct, the onboard Wi-Fi is not compatible with macOS. These two guides have recommendations for PCIe Wi-Fi/Bluetooth modules that will work natively with macOS and AirDrop:

[Glasgood's macOS Mojave [SUCCESS][GUIDE] for Aorus Z390 Pro
](https://www.insanelymac.com/forum/topic/337837-glasgoods-macos-mojave-successguide-for-aorus-z390-pro/)

[[SUCCESS] Gigabyte Designare Z390 (Thunderbolt 3) + i7-9700K + AMD RX 580
](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/)

**Comment by wxy524** [comment]
BCM94360CD is working perfectly oob. 
Another issue I faced was OsxAptioFix3Drv did not work after I migrated system from my macbook pro (only migrated Applicaiton, User and Wifi configuration). To resolve this issue, I replaced OsxAptioFix3Drv to OsxAptioFix2Drv-free2000.efi. The interesting thing is OsxAptioFix3Drv only works fine with iGPU after system migration. My GPU is Nitro+ 5700XT.

BTW, I have to say your instruction is insane. This is the best guild I have ever seen. Thank you very much.

**Comment by shiruken** [comment]
Thanks!

Also, I'd be cautious about using OsxAptioFix2Drv-free2000.efi since it wasn't designed for long-term use (just bug testing) and could potentially damage your motherboard:

* [I unleashed a plague upon you guys and I am sorry for OsxAptioFix2Drv-free2000](https://www.reddit.com/r/hackintosh/comments/cfjyla/i_unleashed_a_plague_upon_you_guys_and_i_am_sorry/)

**Comment by wxy524** [comment]
hmm. however, other memory fix drivers do not work for me. I tried to calculate slide value but never have lucky.  The below error comes constantly (even value). My build is 32gb memory, nitro+ 5700xt and 4k display. Do you have any suggestion that I can murder OsxAptioFix2Drv-free2000.efi ? I tried slide value from 0, 1, 222, 197, 195 and etc. The value in the error message 0x02346000 actually is available based on memmap...(page 0x015FDE). 

Any suggestion will be very appreciated. 

<img width="1131" alt="Screen Shot 2020-02-13 at 12 09 19 AM" src="https://user-images.githubusercontent.com/1792178/74413895-261d4480-4df5-11ea-9362-3a67c25fffb1.png">
<img width="1164" alt="Screen Shot 2020-02-13 at 12 09 26 AM" src="https://user-images.githubusercontent.com/1792178/74413900-27e70800-4df5-11ea-9311-9736976ae940.png">

**Comment by shiruken** [comment]
Unfortunately I'm not super familiar with the process for calculating the `slide` value. I have seen some posts about using [OcQuirks](https://github.com/ReddestDream/OcQuirks) to get around the Aptio issues.

**Comment by wxy524** [comment]
OcQuirks does not work neither. The only way I find that I can rid of OsxAptioFix2Drv-free2000.efi is to clean kext cache every time before restart ```kextcache -i /Volumes/Macintosh\ HD```. 

Anyway, thanks for your suggestion. : )
