### ISSUE TITLE
How to get WiFi working?

### ISSUE THREAD

**Issue by nabilzhafri** [shiruken/hackintosh#7]
Hi, from your parts I dont see you use any external wifi card? May I know how did you get the WiFi working from existing parts? The additional WiFi card can only work for bluetooth I believe.

**Comment by shiruken** [comment]
I actually don't need WiFi so I never bothered with an external card. I assume the standard recommendations from most hackintosh builds will work fine. Regarding the Intel CNVi module on the motherboard, [there is development](https://github.com/AppleIntelWifi/adapter) on a kext that should enable its functionality.
