### ISSUE TITLE
iGPU Required?

### ISSUE THREAD

**Issue by jerryhcooke** [shiruken/hackintosh#8]
I’m planning an extremely similar build with one significant difference (I’m converting an existing windows build):

I’ve got a 9700KF and therefore no iGPU

Will I be fine to inject the kexts for my 5600 XT for the initial install?

**Comment by shiruken** [comment]
Yeah, you should be fine. I [encountered graphical issues](https://www.reddit.com/r/hackintosh/comments/dwr8xv/graphic_glitch_on_5700_xt_and_catalina_10151/) that interfered with the installation of macOS that were fixed in 10.15.2.
